version: '3'
services:
  api:
    build:
      context: ./src/api/v1
      dockerfile: ./Dockerfile
    ports:
      - 4000:3000
    volumes:
      - ./src/api/v1:/usr/src/app/api
      - /usr/src/app/api/node_modules
    environment:
      PORT: 3000
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: node
      MYSQL_USER: test
      MYSQL_PASSWORD: 123123
    command: '--default-authentication-plugin=mysql_native_password'