version: '3'
services:
  api:
    build:
      context: ./src/api/v1
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./src/api/v1:/usr/src/project/api
    environment:
      PORT: 8080
    depends_on:
      - db
  app:
    build:
      context: ./src/app
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./src/app:/usr/src/project/app
    environment:
      PORT: 3000
    depends_on:
      - api
  db:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: node
      MYSQL_USER: test
      MYSQL_PASSWORD: 123123
    command: '--default-authentication-plugin=mysql_native_password'